title: Home

views:
  - title: alarm
    cards:
      - type: sensor
        entity: sensor.pir_stue
     
  - title: sensors
    cards:
      - type: entities
        title: sensors
        entities:
          - sensor.pir_stue

      - type: entities
        title: router
        entities:
          - sensor.rt_ac52u_bytes_received
          - sensor.rt_ac52u_kbyte_sec_received
          - sensor.rt_ac52u_kbyte_sec_sent
