- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /

#- platform: template
#  sensors:
#    rt_ac52u_bytes_sent:
#      value_template: '{{ states.sensor.rt_ac52u_bytes_sent.state | multiply(0.000000000) }}'
#      friendly_name: 'GB sent'
#      unit_of_measurement: 'GB'
##Something like this {{ states.sensor.bytes_sent | filesizeformat() }}/s 

- platform: command_line
  name: PIR_stue
  command: 'python /config/include/python_scripts/PIR_stue.pi'
  scan_interval: 5
  command_timeout: 5
     
- platform: bme280
  name: Ambient
  i2c_address: 0x76
  operation_mode: 2  # forced mode
  time_standby: 5
  oversampling_temperature: 4
  oversampling_pressure: 4
  oversampling_humidity: 4
  delta_temperature: -0.5
  monitored_conditions:
    - temperature
    - humidity
    - pressure
  scan_interval: 40 
